
package mx.gob.imss.catalogos.wsdl.sat;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.5
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SATPatrones", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SATPatrones {


    /**
     * 
     * @param datosEntrada
     * @return
     *     returns mx.gob.imss.catalogos.wsdl.sat.SalidaSAT
     */
    @WebMethod
    @WebResult(targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
    @RequestWrapper(localName = "getPatron", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "mx.gob.imss.catalogos.wsdl.sat.GetPatron")
    @ResponseWrapper(localName = "getPatronResponse", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws", className = "mx.gob.imss.catalogos.wsdl.sat.GetPatronResponse")
    public SalidaSAT getPatron(
        @WebParam(name = "datosEntrada", targetNamespace = "http://mx/gob/imss/didt/cia/interoper/sat/ws")
        EntradaSAT datosEntrada);

}
