
package mx.gob.imss.acuses.wsfirmaelectronicaseg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FirmaElectronicaSegService", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", wsdlLocation = "https://firmadigitalssl.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL")
public class FirmaElectronicaSegService
    extends Service
{

    private static final URL FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION;
    private static final WebServiceException FIRMAELECTRONICASEGSERVICE_EXCEPTION;
    private static final QName FIRMAELECTRONICASEGSERVICE_QNAME = new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://firmadigitalssl.imss.gob.mx/WsFirmaElectronicaSeg/FirmaElectronicaSegService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION = url;
        FIRMAELECTRONICASEGSERVICE_EXCEPTION = e;
    }

    public FirmaElectronicaSegService() {
        super(__getWsdlLocation(), FIRMAELECTRONICASEGSERVICE_QNAME);
    }

    public FirmaElectronicaSegService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRMAELECTRONICASEGSERVICE_QNAME, features);
    }

    public FirmaElectronicaSegService(URL wsdlLocation) {
        super(wsdlLocation, FIRMAELECTRONICASEGSERVICE_QNAME);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRMAELECTRONICASEGSERVICE_QNAME, features);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirmaElectronicaSegService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirmaElectronicaSegPortType
     */
    @WebEndpoint(name = "FirmaElectronicaSegPortTypePort")
    public FirmaElectronicaSegPortType getFirmaElectronicaSegPortTypePort() {
        return super.getPort(new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegPortTypePort"), FirmaElectronicaSegPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirmaElectronicaSegPortType
     */
    @WebEndpoint(name = "FirmaElectronicaSegPortTypePort")
    public FirmaElectronicaSegPortType getFirmaElectronicaSegPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl", "FirmaElectronicaSegPortTypePort"), FirmaElectronicaSegPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRMAELECTRONICASEGSERVICE_EXCEPTION!= null) {
            throw FIRMAELECTRONICASEGSERVICE_EXCEPTION;
        }
        return FIRMAELECTRONICASEGSERVICE_WSDL_LOCATION;
    }

}
