
package mx.gob.imss.acuses.wsfirmaelectronicaseg;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FirmaElectronicaSegPortType", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirmaElectronicaSegPortType {


    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.RegistroSeguimientoResponseType
     */
    @WebMethod(operationName = "RegistroSeguimiento", action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/RegistroSeguimiento")
    @WebResult(name = "RegistroSeguimientoResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public RegistroSeguimientoResponseType registroSeguimiento(
        @WebParam(name = "RegistroSeguimientoRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RegistroSeguimientoRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.FirmaSimpleResponseType
     */
    @WebMethod(operationName = "FirmaSimple", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaSimple")
    @WebResult(name = "FirmaSimpleResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaSimpleResponseType firmaSimple(
        @WebParam(name = "FirmaSimpleRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaSimpleRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.FirmaXMLSegResponseType
     */
    @WebMethod(operationName = "FirmaXML", action = "http://idtrust.metatrust.com.mx/WsFirmaElectronicaSeg/FirmaXML")
    @WebResult(name = "FirmaXMLSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaXMLSegResponseType firmaXML(
        @WebParam(name = "FirmaXMLSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaXMLSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.ConfirmaCveSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/confirmaClaves")
    @WebResult(name = "ConfirmaCveSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public ConfirmaCveSegResponseType confirmaClaves(
        @WebParam(name = "ConfirmaCveSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ConfirmaCveSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.ConsultaCertSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/consultaCertificado")
    @WebResult(name = "ConsultaCertSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public ConsultaCertSegResponseType consultaCertificado(
        @WebParam(name = "ConsultaCertSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ConsultaCertSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.EliminaCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/eliminaClaves")
    @WebResult(name = "EliminaCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public EliminaCvesSegResponseType eliminaClaves(
        @WebParam(name = "EliminaCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        EliminaCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.FirmaSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/firma")
    @WebResult(name = "FirmaSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaSegResponseType firma(
        @WebParam(name = "FirmaSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.GeneraCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/generaClaves")
    @WebResult(name = "GeneraCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public GeneraCvesSegResponseType generaClaves(
        @WebParam(name = "GeneraCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GeneraCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.RegistraCvesSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/registraClaves")
    @WebResult(name = "RegistraCvesSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public RegistraCvesSegResponseType registraClaves(
        @WebParam(name = "RegistraCvesSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RegistraCvesSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.ValidaFirmaSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaFirma")
    @WebResult(name = "ValidaFirmaSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public ValidaFirmaSegResponseType validaFirma(
        @WebParam(name = "ValidaFirmaSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaFirmaSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.RecuperaArchivoResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/recuperaArchivo")
    @WebResult(name = "RecuperaArchivoResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public RecuperaArchivoResponseType recuperaArchivo(
        @WebParam(name = "RecuperaArchivoRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        RecuperaArchivoRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.ValidaCertificadoSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaCertificado")
    @WebResult(name = "ValidaCertificadoSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public ValidaCertificadoSegResponseType validaCertificado(
        @WebParam(name = "ValidaCertificadoSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaCertificadoSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.ValidaCMSV2ResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/validaCMSV2")
    @WebResult(name = "ValidaCMSV2Response", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public ValidaCMSV2ResponseType validaCMSV2(
        @WebParam(name = "ValidaCMSV2Request", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        ValidaCMSV2RequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.FirmaLoteResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/firmaLote")
    @WebResult(name = "FirmaLoteResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public FirmaLoteResponseType firmaLote(
        @WebParam(name = "FirmaLoteRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        FirmaLoteRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.HashSegResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getHash")
    @WebResult(name = "HashSegResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public HashSegResponseType getHash(
        @WebParam(name = "HashSegRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        HashSegRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.GetSignerDataResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getSignerData")
    @WebResult(name = "GetSignerDataResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public GetSignerDataResponseType getSignerData(
        @WebParam(name = "GetSignerDataRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GetSignerDataRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.GetCMSContentResponseType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getCMSContent")
    @WebResult(name = "GetCMSContentResponse", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public GetCMSContentResponseType getCMSContent(
        @WebParam(name = "GetCMSContentRequest", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GetCMSContentRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.GetTimeStampRespType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getTimeStamp")
    @WebResult(name = "GetTimeStampResp", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public GetTimeStampRespType getTimeStamp(
        @WebParam(name = "GetTimeStampReq", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GetTimeStampReqType body);

    /**
     * 
     * @param body
     * @return
     *     returns mx.gob.imss.firmadigitalssl.wsfirmaelectronicaseg.GetTimeStampDataRespType
     */
    @WebMethod(action = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg/getTimeStampData")
    @WebResult(name = "GetTimeStampDataResp", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
    public GetTimeStampDataRespType getTimeStampData(
        @WebParam(name = "GetTimeStampDataReq", targetNamespace = "http://doctrust.metatrust.com.mx/WsFirmaElectronicaSeg.xsd", partName = "body")
        GetTimeStampDataReqType body);

}
